"""PWA sidecar assets for the static export — manifest, service worker, icons.

The read-only page (export.py) is the whole product surface for the public
mobile app. Making it an *installable, offline-capable* PWA is what lets the
Capacitor wrapper (and a plain "add to home screen") behave like a real app —
and the offline cache is one of the native-value features that answers Apple's
4.2 "just a repackaged website" rejection.

This module writes the three sidecar files next to index.html:
  • manifest.webmanifest — name, icons, standalone display, theme color
  • sw.js               — app-shell cache-first + data.json network-first
  • icon-*.png / icon.svg — copied from the committed static/pwa set

The <link>/<meta> head tags, the service-worker registration, and the
first-run disclaimer gate live in export.py's template (so the HTML is
self-describing); this module only emits the files those tags point at.
Everything is degrade-safe: a missing icon source is skipped, never raised.
"""
from __future__ import annotations

import json
import pathlib
import shutil

_ICON_SRC = pathlib.Path(__file__).parent / "static" / "pwa"
_ICON_FILES = (
    "icon-192.png", "icon-512.png", "icon-maskable-512.png",
    "apple-touch-icon-180.png", "icon.svg",
)

MANIFEST: dict = {
    "name": "surge — 야간 방향 콜",
    "short_name": "surge",
    "description": "미국 야간 세션 방향 예측의 사후 검증 기록 — 참고·교육용, 투자자문 아님.",
    "lang": "ko",
    "dir": "ltr",
    "start_url": "./",
    "scope": "./",
    "display": "standalone",
    "orientation": "portrait",
    "background_color": "#10151A",
    "theme_color": "#2E7D6B",
    "categories": ["finance", "education"],
    "icons": [
        {"src": "icon-192.png", "sizes": "192x192", "type": "image/png",
         "purpose": "any"},
        {"src": "icon-512.png", "sizes": "512x512", "type": "image/png",
         "purpose": "any"},
        {"src": "icon-maskable-512.png", "sizes": "512x512",
         "type": "image/png", "purpose": "maskable"},
        {"src": "icon.svg", "sizes": "any", "type": "image/svg+xml",
         "purpose": "any"},
    ],
}

# App-shell precache + runtime strategy. data.json is network-first so a fresh
# call loads when online and the last cached one shows offline; the shell is
# cache-first so the app opens instantly and works with no connection.
SERVICE_WORKER = r"""// surge PWA service worker — generated by surge.dashboard.pwa
const CACHE = 'surge-shell-v1';
const SHELL = [
  './', './index.html', './manifest.webmanifest',
  './icon-192.png', './icon-512.png', './icon-maskable-512.png',
  './apple-touch-icon-180.png', './icon.svg'
];
self.addEventListener('install', (e) => {
  e.waitUntil(caches.open(CACHE).then((c) => c.addAll(SHELL))
    .then(() => self.skipWaiting()).catch(() => {}));
});
self.addEventListener('activate', (e) => {
  e.waitUntil(caches.keys().then((ks) => Promise.all(
    ks.filter((k) => k !== CACHE).map((k) => caches.delete(k))))
    .then(() => self.clients.claim()));
});
self.addEventListener('fetch', (e) => {
  const req = e.request;
  if (req.method !== 'GET') return;
  const url = new URL(req.url);
  if (url.pathname.endsWith('data.json')) {          // fresh calls: network-first
    e.respondWith(fetch(req).then((r) => {
      const cp = r.clone(); caches.open(CACHE).then((c) => c.put(req, cp));
      return r;
    }).catch(() => caches.match(req)));
    return;
  }
  e.respondWith(caches.match(req).then((hit) => hit || fetch(req).then((r) => {
    if (r.ok && url.origin === location.origin) {
      const cp = r.clone(); caches.open(CACHE).then((c) => c.put(req, cp));
    }
    return r;
  }).catch(() => caches.match('./index.html'))));
});
"""


def write_pwa_assets(outdir: str | pathlib.Path) -> list[str]:
    """Write manifest.webmanifest + sw.js and copy the icon set into `outdir`.
    Returns the filenames written. Degrade-safe: a missing icon is skipped."""
    out = pathlib.Path(outdir)
    out.mkdir(parents=True, exist_ok=True)
    written: list[str] = []

    (out / "manifest.webmanifest").write_text(
        json.dumps(MANIFEST, ensure_ascii=False, indent=2), encoding="utf-8")
    written.append("manifest.webmanifest")

    (out / "sw.js").write_text(SERVICE_WORKER, encoding="utf-8")
    written.append("sw.js")

    for name in _ICON_FILES:
        src = _ICON_SRC / name
        if src.exists():
            shutil.copyfile(src, out / name)
            written.append(name)
    return written
